config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  get 'robots.txt', to: 'catalog#robots'
  get 'error/:number', to: 'catalog#error', as: :error

  post 'p/comment', to: 'products#add_comment', as: :product_comment
  get '/c/:id/compare', to: 'categories#compare', as: :compare
  post '/c/:id/compare/:product_id', to: 'categories#add_to_compare', as: :add_to_compare
  delete '/c/:id/compare/:product_id', to: 'categories#remove_from_compare', as: :remove_from_compare

  get 'p/:slug-:id', to: 'products#show', as: :p
  get 't/:slug-:id', to: 'taxons#show', as: :t
  get 'c/:slug-:id', to: 'categories#show', as: :c
  get 'pages/:slug-:id', to: 'catalog#static_page', as: :static_page
  get 'help/:slug-:id', to: 'catalog#show_help_page', as: :help_page

  # Old links for SEO
  get 'p/:slug/:id', to: redirect('/p/%{slug}-%{id}')
  get 't/:slug/:id', to: redirect('/t/%{slug}-%{id}')
  get 'c/:slug/:id', to: redirect('/c/%{slug}-%{id}')
  get 'pages/:slug/:id', to: redirect('/pages/%{slug}-%{id}')
  get 'help/:slug/:id', to: redirect('/help/%{slug}-%{id}')

  devise_for :users
  resource :user, only: [:show, :update] do
    post :callback
  end

  get 'help', to: 'catalog#help_pages', as: :help_pages
  get 'p/search', to: 'products#search', as: :search_products

  resource :order, only: [:show, :update] do
    post :checkout
    patch 'update_lineitem_count', to: 'orders#update_lineitem_count', as: :update_lineitem_count
    post 'add_product/:product_id', to: 'orders#add_product', as: :add_product
    delete 'remove_product/:product_id', to: 'orders#remove_product', as: :remove_product
  end

  namespace :admin do
    get '/', to: 'base#dashboard'
    post 'internal/:act', to: 'base#internal', as: :internal_action
    post 'binding/:product_id/:vendor_product_id', to: 'binding#bind'
    delete 'binding/:vendor_product_id', to: 'binding#unbind'
    namespace :autocomplete do
      get :properties
    end
    resources :taxons do
      post :sort, on: :collection
    end
    resources :products do
      member do
        post :update_from_marketplace
        post :recount
        post :copy_filters
        post :copy_properties
        patch 'product_filter_values/:pfv_id', to: 'products#update_product_filter_value', as: :update_pfv
      end
      collection do
        get :search
        get :search_marketplaces
        post :create_from_marketplace
      end
      resources :product_properties, only: [:create, :update] do
        member do
          patch :update, to: 'properties#update_product_property', as: :update
          delete :destroy, to: 'properties#destroy_product_property', as: :destroy
        end
        collection do
          post :create, to: 'properties#create_product_property', as: :create
        end
      end
      resources :properties, only: [:create, :destroy] do
        collection do
          patch :reorder_product
        end
      end

    end
    resources :categories, except: [:show] do
      post :reorder_all_properties
      post :reorder_filters
      post :add_filter
      post :add_filter_value
      delete 'remove_filter/:filter_id', to: 'categories#remove_filter', as: :remove_filter
      delete 'remove_filter_value/:filter_value_id', to: 'categories#remove_filter_value', as: :remove_filter_value
      resources :properties, only: [] do
        member do
          delete :'destroy_category_property', as: :destroy
        end
        collection do
          post :create_category_property, as: :create

          patch :reorder_category
          post :reorder_category_all
        end
      end
      collection do
        get :search
      end
    end

    resources :brands, except: [:show] do
      collection do
        get :search
      end
    end
    resources :confs, only: [:index, :update]
    resources :markups, except: [:show] do
      get :search, on: :collection
    end
    resources :orders, except: [:show] do
      get :search, on: :collection
    end
    resources :users, except: [:show] do
      get :search, on: :collection
    end
    namespace :vendor do
      resources :products, only: [:index, :show, :update] do
        get :search, on: :collection
        post :toggle_activation, on: :member
      end
      resources :merchants, except: [:show] do
        post :pricelist, on: :member
        get :auto_price, on: :member
      end
    end
    resources :callbacks, except: [:new, :create, :show] do
      get :search, on: :collection
    end
    resources :comments, except: [:new, :create, :show] do
      get :search, on: :collection
    end
    resources :markups, except: :show
    resources :users, except: [:new, :create, :show]
    resources :user_actions, only: :index do
      get :search, on: :collection
    end
    resources :filters, except: :show
    resources :filter_values, except: :show do
      get :search, on: :collection
    end
    resources :properties
  end
  mount Ckeditor::Engine => '/ckeditor'
end

app/models/order.rb
class Order < ActiveRecord::Base
  STATES = %w{in_cart checkout completed deny in_cart_products}
  store_accessor :info, :phone, :name, :address, :comment,
    :payment_type, :delivery_type, :delivery_cost, :creation_way
  belongs_to :user
  has_many :products, through: :line_items
  has_many :line_items, dependent: :destroy

  # PHONE_OPERATORS = %w(63 93 50 97 96 572).join('|')
  # validates :phone, format: { with: /\A(380)(#{PHONE_OPERATORS})\d{6,7}\Z/ }, allow_blank: true
  validates :phone, format: { with: /\A(380)\d{9}\Z/ }, allow_blank: true
  before_validation :strip_phone

  #scope :payd, -> { where(state: 'payd') }
  #scope :unknown, -> { where(user: nil) }
  scope :in_cart,   -> { includes(:line_items).where(line_items: { order_id: nil }, orders: {state: 'in_cart'}) }
  scope :in_cart_products,   -> { joins(:line_items).where("orders.state = 'in_cart'") }
  scope :completed, -> { where("orders.state = 'completed'") }
  scope :checkout,  -> { where("orders.state = 'checkout'") }
  scope :deny,      -> { where("orders.state = 'deny'") }

  scope :by_month,  -> (month) { where('orders.created_at >= ? AND orders.created_at <= ?', Date.new(Date.today.year, month.to_i, 1), Date.new(Date.today.year, month.to_i, 1).end_of_month) }

  accepts_nested_attributes_for :line_items, allow_destroy: true
  accepts_nested_attributes_for :user

  class << self
    def ransackable_scopes(auth_object = nil)
      [:by_month, :by_state]
    end

    def by_state(state)
      return false unless state.to_s.in?(STATES)
      all.send(state)
    end

    def payment_types
      Conf['txt.payment_types'].split("\n").map(&:strip)
    end

    def delivery_types
      Conf['txt.delivery_types'].split("\n").map(&:strip)
    end
  end

  def admin_order_product=(product_id)
    add_product(product_id, 1, true)
  end

  def admin_order_product
    ''
  end

  def order_product=(product_id)
    add_product(product_id)
  end

  def order_product
  end

  def add_product(product, quantity=1, admin=false)
    product = product.kind_of?(Catalog::Product) ? product : Catalog::Product.where(id: product).first
    if product && product.price > 0
      if already_added = line_items.detect{ |li| li.product == product }
        quantity = quantity + already_added.quantity
        if admin
          pr = product.price * quantity
          v_pr = product.in_price * quantity
          already_added.update(quantity: quantity, price: pr.ceil, vendor_price: v_pr.ceil)
        else
          already_added.update(quantity: quantity)
        end
      else
        if admin
          line_items.create(product: product, quantity: quantity, price: product.price, vendor_price: product.in_price)
        else
          line_items.create(product: product, quantity: quantity)
        end
      end


    else
      false
    end

  end

  def add_comment=(value)
    txt = comment.to_s << value
    self.comment = txt
  end

  def add_comment
    ""
  end

  def display_comment
     # TODO: XSS
    comment.to_s.split("<hr/>").reverse.join("<hr/>").html_safe
  end

  def items_count
    line_items.map(&:quantity).sum
  end

  def ready?
    valid? && %w(name phone).all?{ |field| self.send(field).present? }
  end

  def total_sum
    line_items.includes(:product, :order).map { |li| li.quantity * li.client_price } .sum
  end

  def total_income
    line_items.includes(:product).map(&:income).sum
  end

  def format_phone
    ActionController::Base.helpers.number_to_phone(phone[3..-1], country_code: 380)
  end

  def credit_names
    line_items.map do |li|
      name = "#{li.product.name}"
      name << "(x#{li.quantity})" if li.quantity > 1
      name
    end
  end

  private

  def strip_phone
    return if new_record? || (p = self[:info]["phone"].to_s).blank?
    p.gsub!(/[^\d]/, '')
    unless p =~ /\A38/
      p = "38#{p}"
    end
    self.phone = p
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController
  before_action :check_admin_permissions
  before_action :set_order, only: [:edit, :update]
  def index
    @q = Order.includes(products: { vendor_products: :merchant }, line_items: :order, user: :orders).ransack(search_params)
    @all_orders = @q.result.order('orders.completed_at DESC NULLS LAST')
    @orders = @all_orders.page(params[:page])
  end

  def edit
  end

  def update
    if params[:order].try(:[], :line_items_attributes)
      params[:order][:line_items_attributes].each do |li|
        if li.last[:quantity] == '0'
          @order.line_items.find(li.last[:id]).destroy
          params[:order][:line_items_attributes].delete(li.first)
        end
      end
    end
    if @order.update(order_params)
       redirect_to :back
    else
      render :edit
    end
  end

  def create
    @order = Order.new(admin_order_params)
    if @order.save
      redirect_to edit_admin_order_path(@order)
    else
      render :new
    end
  end

  def new
    @order = Order.new
  end

  def search
    @q = Order.includes(:products, line_items: :order, user: :orders).ransack(search_params)
    @all_orders = @q.result.order('orders.completed_at DESC NULLS LAST')
    @orders = @all_orders.page(params[:page])
    render :index
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    c = params.try(:[], :order).try(:[], :add_comment)
    if c.present?
      named_comment = %(<hr/><b>#{current_user.name}</b>: #{c} <div class='text-right'> #{Time.now.strftime("%x %X")}</div>)
      params[:order][:add_comment] = named_comment
    end
    params.require(:order).permit(:name, :phone, :state, :user_id, :address,
      :add_comment, :payment_type, :delivery_type, :admin_order_product,
      line_items_attributes: [:quantity, :price, :vendor_price, :id, :vendor, :serial_numbers])
  end

  def admin_order_params
    params[:order][:creation_way] = 'admin'
    params.require(:order).permit(:name, :phone, :user, :address,
      :payment_type, :delivery_type, :state, :creation_way)
  end

  def search_params
    if params[:q]
      params[:q].each do |k, v|
        params[:q][k] = params[:q][k].strip
        params[:q].delete(k) if params[:q][k].blank?
      end
    else
      params[:q] = {}
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < CatalogController

  def update
    @current_order.update(order_params)
    respond_to do |format|
      format.js do
        @render_hash = {
          partial: 'orders/form',
          layout: false,
          locals: {
            order: @current_order,
            instant: false,
            product_id: nil
          }
        }
      end
    end
  end

  def show
  end

  def checkout
    if params[:order].try(:[], :super_instant) == 'true'
      @current_order.line_items.destroy_all
      phone = Catalog.strip_phone(params[:order][:phone])
      @current_order.add_product(params[:order][:product_id])
      @current_order.update!(creation_way: 'instant_checkout', name: 'Купил в 1 клик', phone: phone)
    end
    head 422 and return unless @current_order.ready?
    if params[:instant] == 'true'
      @current_order.line_items.destroy_all
      @current_order.add_product(params[:product_id])
      @current_order.update(creation_way: 'instant_checkout')
    end
    pass = Devise.friendly_token
    user = User.where(phone: @current_order.phone).first_or_create!(email: "#{@current_order.phone}@kiosk.evotex.kh.ua", password: pass, password_confirmation: pass)
    if @current_order.creation_way == 'instant_checkout'
      creation_way = 'instant_checkout'
    elsif current_user.try(:admin?)
      creation_way = 'admin'
    else
      creation_way = 'default'
    end
    @current_order.line_items.map(&:fix_price!)
    @current_order.update!(state: 'checkout', user: user, completed_at: Time.now, creation_way: creation_way)
    session[:order_id] = nil
    if session[:ordered].present?
      session[:ordered] = session[:ordered].to_s << " #{@current_order.id}"
    else
      session[:ordered] = @current_order.id.to_s
    end
    redirect_to user_path(ordered: true), notice: "Заказ успешно оформлен. Номер заказа: #{@current_order.id}"
  end

  def update_lineitem_count
    params[:line_items].each do |id, values|
      q = values[:quantity]
      li = @current_order.line_items.find(id)
      if q.to_i < 1
        li.destroy
      else
        li.update(quantity: q)
      end
    end
    respond_to do |format|
      format.js { head 200 }
      format.html { redirect_to order_path }
    end
  end

  def remove_product
    @current_order.line_items.where(catalog_product_id: params[:product_id]).first.destroy
    redirect_to order_path
  end

  def add_product
    if @current_order.add_product(params[:product_id])
      redirect_to order_path
    else
      head 422
    end
  end

  private

  def order_params
    if params[:order][:phone].blank?
      params[:order][:phone] = nil
      params[:order].permit(:name, :address, :phone, :comment, :delivery_type, :payment_type)
    else
      params[:order].permit(:name, :phone, :address, :comment, :delivery_type, :payment_type)
    end

  end

end

app/views/admin/orders/_actions.html.haml
= link_to edit_admin_order_path(order), class: 'btn btn-primary btn-xs' do
  %i.glyphicon.glyphicon-edit

app/views/admin/orders/_client_info.html.haml
%ul.nav.nav-tabs
  - if user = order.user
    %li{ class: ('active' if order.products.blank?)}= link_to "Клиент", "#order_#{order.id}_client", 'data-toggle' => 'tab'
  - if order.products.present?
    %li.active= link_to "Товары (#{order.items_count})", "#order_#{order.id}_products", 'data-toggle' => 'tab'
  - if order.comment.present?
    %li= link_to "Комментарии (#{order.comment.to_s.split('<hr/>').count})", "#order_#{order.id}_comments", 'data-toggle' => 'tab'
.tab-content
  - if user = order.user
    .tab-pane{ id: "order_#{order.id}_client", class: ('active' if order.products.blank?) }
      %table.table.table-bordered.color-black
        %tr
          %td Имя
          %td
            =link_to edit_admin_user_path(user) do
              = user.name.presence || 'не указано'
        %tr
          %td Телефон
          %td= number_to_phone(user.phone[3..-1], country_code: 380) rescue '-'
        %tr
          %td Всего потратил
          %td #{user.total_income} грн.
        %tr
          %td Принес прибыли
          %td #{user.clean_total_income} грн.
  - if order.products.present?
    .tab-pane.active{ id: "order_#{order.id}_products" }
      %table.table.table-bordered.color-black
        %tr
          %th Название
          %th.text-center Кол-во
          %th.text-center Цена
          %th.text-center Поставщик
        - order.line_items.each do |li|
          %tr
            %td= link_to li.product.name, edit_admin_product_path(li.product)
            %td= li.quantity
            %td #{li.product.price} грн.
            %td
              - if li.product.fixed_price?
                Фикс. цена
              - else
                - m = li.product.active_vendor.try(:merchant)
                - if m
                  = link_to m.name, edit_admin_vendor_merchant_path(m)
                - else
                  Поставщик не найден
  - if order.comment.present?
    .tab-pane{ id: "order_#{order.id}_comments" }
      %pre.comment
        = order.display_comment

app/views/admin/orders/_common_info.html.haml
.text-right
  .badge ##{order.id}
%br/
.label{ class: order.state }= t("orders.states.#{order.state}")
.label.label-default= t("orders.creation_ways.#{order.creation_way || 'missing'}")
.label.label-primary{ title: 'Время появления пользователя' }
  = I18n.l(order.created_at, format: "%e %b, %H:%M")
.label.label-primary{ title: 'Время последнего обновления' }
  = I18n.l(order.updated_at, format: "%e %b, %H:%M")
- if order.completed_at.present?
  .label.label-primary{ title: 'Время оформления заказа' }
    = I18n.l(order.completed_at, format: "%e %b, %H:%M")
.label{ class: ( order.total_income >= 0 ? 'label-success' : 'label-danger') }
  = order.total_sum - order.total_income
  \/
  = order.total_sum
  (#{order.total_income})
= link_to edit_admin_order_path(order), class: 'label btn btn-primary btn-xs' do
  %i.glyphicon.glyphicon-edit
  Редактировать

app/views/admin/orders/_form.html.haml
.row
  .col-sm-4
    = form_for(@order, url: @order.persisted? ? admin_order_path(@order) : admin_orders_path , remote: @order.persisted?, data: { autoupdate: @order.persisted? }) do |f|
      = render 'shared/error_messages', object: f.object
      %ul.list-group
        %li.list-group-item= field_for f, :name
        %li.list-group-item= field_for f, :phone, :phone_field
        %li.list-group-item= select_field_for f, :user_id, User.all.map{ |u| [u.form_display, u.id] }
        %li.list-group-item= select_field_for f, :state, Order::STATES.map{ |s| [t("orders.states.#{s}"), s] }
        %li.list-group-item= select_field_for f, :payment_type,  Order.delivery_types
        %li.list-group-item= select_field_for f, :delivery_type, Order.payment_types
        %li.list-group-item= field_for f, :delivery_cost
        %li.list-group-item= field_for f, :address, :text_area, rows: 8
      .form-actions
        - if @order.new_record?
          = f.submit 'Создать заказ', class: 'btn btn-success'
  .col-sm-4
    %pre.comment= comment
    = form_for(@order, url: @order.persisted? ? admin_order_path(@order) : admin_orders_path) do |f|
      = field_for f, :add_comment, :text_area, rows: 8
      .form-actions
        = f.submit 'Отправить', class: 'btn btn-success'
  .col-sm-4
    = form_for(@order, url: @order.persisted? ? admin_order_path(@order) : admin_orders_path) do |f|
      = f.text_field :admin_order_product, class: 'form-control'
      %small Артикул товара
      .form-actions
        = f.submit 'Добавить товар', class: 'btn btn-success'
    %br/
    = form_for(@order, url: @order.persisted? ? admin_order_path(@order) : admin_orders_path) do |f|
      =# render @order.line_items.includes(:product, :order), f: f
      = f.fields_for :line_items do |li|
        = render 'line_items_attributes', li: li
      .form-actions
        = f.submit 'Обновить', class: 'btn btn-success'

app/views/admin/orders/_line_items_attributes.html.haml
.panel.panel-default
  .panel-heading
    %h3.panel-title
      %small.pull-right= li.object.product.id
      = link_to li.object.product.name, edit_admin_product_path(li.object.product)
  .panel-body
    = li.select :vendor, options_for_select(Vendor::Merchant.all.map{ |m| [m.name] }, li.object.vendor), {},class: 'form-control'
    %br/
    .row

      .container-fluid

        .col-sm-4
          .row
            .text-center
              = link_to edit_admin_product_path(li.object.product) do
                = image_tag 'lazy-spinner.gif', class: 'img-responsive thumbnail lazy', 'data-original' => presents(li.object.product).preview_path
              %small ( #{li.object.quantity} шт. )
              %br/


        .col-sm-8

          %table.table.table-bordered.color-black
            %tr
              %td Цена
              %td= li.object.client_price
            %tr
              %td Вход
              %td= li.object.in_price
            %tr
              %td Прибыль
              %td= li.object.income
        .col-xs-12
          = field_for li, :serial_numbers, :text_area, rows: li.object.quantity


  .panel-footer
    .row
      .col-sm-6
        #{li.object.price} грн. шт.
      .col-sm-6
        = li.number_field :quantity, class: 'form-control'

app/views/admin/orders/_order.html.haml
%tr
  %td.orders-table_common-info
    = render 'common_info', order: order
  %td.orders-table_order-info{ colspan: (order.user || order.products.present?) ? 0 : 2 }
    = render 'order_info', order: order
  - if order.user || order.products.present?
    %td.orders-table_client-info
      = render 'client_info', order: order

app/views/admin/orders/_order_info.html.haml
%table.table.table-bordered.color-black
  %tr
    %td Имя
    %td= order.name.presence || 'не указано'
  %tr
    %td Телефон
    %td= number_to_phone(order.phone[3..-1], country_code: 380) rescue '-'
  %tr
    %td Адрес
    %td= order.address
  %tr
    %td Доставка
    %td= order.delivery_type
  %tr
    %td Оплата
    %td= order.payment_type

app/views/admin/orders/edit.html.haml
.page-header
  = link_to admin_orders_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Назад
  .label{ class: @order.state }= t("orders.states.#{@order.state}")
  %h1
    Заказ №
    = @order.id
    %small
      К оплате:
      %b #{@order.total_sum} грн.
      Прибыль:
      %b #{@order.total_income} грн.
= render 'form', comment: @order.display_comment

app/views/admin/orders/index.html.haml
.jumbotron
  = search_form_for @q, url: search_admin_orders_path do |f|
    .row
      .col-sm-12
        .form-group
          = f.search_field :id_eq, class: 'form-control', placeholder: 'Номер'
      .col-sm-4
        .form-group
          = f.select :by_month, options_for_select((1..12).map{ |i| [I18n.l(Date.new(Date.today.year, i, 1), format: "%b"), i] }, params[:q][:by_month]), {include_blank: 'Выберите месяц'}, class: 'form-control select2'
      .col-sm-4
        .form-group
          = f.select :user_id_eq, options_for_select(User.all.map{ |u| [u.form_display, u.id] }, params[:q][:user_id_eq]), {include_blank: 'Выберите клиента'}, class: 'form-control select2'
      .col-sm-4
        .form-group
          = f.select :by_state, options_for_select(Order::STATES.map{ |s| [t("orders.states.#{s}"), s] }, params[:q][:by_state]), {include_blank: 'Выберите состояние'}, class: 'form-control select2'

    .row
      .col-sm-3
        .form-group
          = f.label :completed_at_gteq, 'Завершен после'
          = f.date_field :completed_at_gteq, class: 'form-control', placeholder: 'Завершен после'
      .col-sm-3
        .form-group
          = f.label :completed_at_lteq, 'Завершен до'
          = f.date_field :completed_at_lteq, class: 'form-control', placeholder: 'Завершен до'
      .col-sm-3
        .form-group
          = f.label :created_at_gteq, 'Создан после'
          = f.date_field :created_at_gteq, class: 'form-control', placeholder: 'Создан после'
      .col-sm-3
        .form-group
          = f.label :created_at_lteq, 'Создан до'
          = f.date_field :created_at_lteq, class: 'form-control', placeholder: 'Создан до'
    .form-actions
      = f.submit 'Найти', class: 'btn btn-success'

.page-header
  = link_to new_admin_order_path, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    Новый заказ
  %h1
    Заказы
    %small (#{@all_orders.count})

- if @orders.present?
  .table-responsive
    %table.table.table-bordered.table-hover.orders-table
      %thead
        %tr
          %th Инфо
          %th Заказ
          %th Дополнительно
      %tbody= render @orders
      %tfooter
        %tr
          %td.text-center{ colspan: 4 }= paginate @orders
- else
  По данному фильтру заказы не найдены

app/views/admin/orders/new.html.haml
.page-header
  = link_to admin_orders_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Назад
  %h1
    Новый заказ
= render 'form', comment: ''