config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  get 'robots.txt', to: 'catalog#robots'
  get 'error/:number', to: 'catalog#error', as: :error

  post 'p/comment', to: 'products#add_comment', as: :product_comment
  get '/c/:id/compare', to: 'categories#compare', as: :compare
  post '/c/:id/compare/:product_id', to: 'categories#add_to_compare', as: :add_to_compare
  delete '/c/:id/compare/:product_id', to: 'categories#remove_from_compare', as: :remove_from_compare

  get 'p/:slug-:id', to: 'products#show', as: :p
  get 't/:slug-:id', to: 'taxons#show', as: :t
  get 'c/:slug-:id', to: 'categories#show', as: :c
  get 'pages/:slug-:id', to: 'catalog#static_page', as: :static_page
  get 'help/:slug-:id', to: 'catalog#show_help_page', as: :help_page

  # Old links for SEO
  get 'p/:slug/:id', to: redirect('/p/%{slug}-%{id}')
  get 't/:slug/:id', to: redirect('/t/%{slug}-%{id}')
  get 'c/:slug/:id', to: redirect('/c/%{slug}-%{id}')
  get 'pages/:slug/:id', to: redirect('/pages/%{slug}-%{id}')
  get 'help/:slug/:id', to: redirect('/help/%{slug}-%{id}')

  devise_for :users
  resource :user, only: [:show, :update] do
    post :callback
  end

  get 'help', to: 'catalog#help_pages', as: :help_pages
  get 'p/search', to: 'products#search', as: :search_products

  resource :order, only: [:show, :update] do
    post :checkout
    patch 'update_lineitem_count', to: 'orders#update_lineitem_count', as: :update_lineitem_count
    post 'add_product/:product_id', to: 'orders#add_product', as: :add_product
    delete 'remove_product/:product_id', to: 'orders#remove_product', as: :remove_product
  end

  namespace :admin do
    get '/', to: 'base#dashboard'
    post 'internal/:act', to: 'base#internal', as: :internal_action
    post 'binding/:product_id/:vendor_product_id', to: 'binding#bind'
    delete 'binding/:vendor_product_id', to: 'binding#unbind'
    namespace :autocomplete do
      get :properties
    end
    resources :taxons do
      post :sort, on: :collection
    end
    resources :products do
      member do
        post :update_from_marketplace
        post :recount
        post :copy_filters
        post :copy_properties
        patch 'product_filter_values/:pfv_id', to: 'products#update_product_filter_value', as: :update_pfv
      end
      collection do
        get :search
        get :search_marketplaces
        post :create_from_marketplace
      end
      resources :product_properties, only: [:create, :update] do
        member do
          patch :update, to: 'properties#update_product_property', as: :update
          delete :destroy, to: 'properties#destroy_product_property', as: :destroy
        end
        collection do
          post :create, to: 'properties#create_product_property', as: :create
        end
      end
      resources :properties, only: [:create, :destroy] do
        collection do
          patch :reorder_product
        end
      end

    end
    resources :categories, except: [:show] do
      post :reorder_all_properties
      post :reorder_filters
      post :add_filter
      post :add_filter_value
      delete 'remove_filter/:filter_id', to: 'categories#remove_filter', as: :remove_filter
      delete 'remove_filter_value/:filter_value_id', to: 'categories#remove_filter_value', as: :remove_filter_value
      resources :properties, only: [] do
        member do
          delete :'destroy_category_property', as: :destroy
        end
        collection do
          post :create_category_property, as: :create

          patch :reorder_category
          post :reorder_category_all
        end
      end
      collection do
        get :search
      end
    end

    resources :brands, except: [:show] do
      collection do
        get :search
      end
    end
    resources :confs, only: [:index, :update]
    resources :markups, except: [:show] do
      get :search, on: :collection
    end
    resources :orders, except: [:show] do
      get :search, on: :collection
    end
    resources :users, except: [:show] do
      get :search, on: :collection
    end
    namespace :vendor do
      resources :products, only: [:index, :show, :update] do
        get :search, on: :collection
        post :toggle_activation, on: :member
      end
      resources :merchants, except: [:show] do
        post :pricelist, on: :member
        get :auto_price, on: :member
      end
    end
    resources :callbacks, except: [:new, :create, :show] do
      get :search, on: :collection
    end
    resources :comments, except: [:new, :create, :show] do
      get :search, on: :collection
    end
    resources :markups, except: :show
    resources :users, except: [:new, :create, :show]
    resources :user_actions, only: :index do
      get :search, on: :collection
    end
    resources :filters, except: :show
    resources :filter_values, except: :show do
      get :search, on: :collection
    end
    resources :properties
  end
  mount Ckeditor::Engine => '/ckeditor'
end

app/views/shared/_admin_extended_footer_menu.html.haml
- if current_user.try(:admin?)
  .col-sm-3
    %ul.list-group
      %li.list-group-item= link_to 'Новый заказ', new_admin_order_path
      %li.list-group-item= link_to 'Все заказы', admin_orders_path
      %li.list-group-item= link_to 'Новый пользователь', new_admin_user_path
      %li.list-group-item= link_to 'Все пользователи', admin_users_path
      %li.list-group-item= link_to 'Комментарии к товарам', admin_comments_path
      %li.list-group-item= link_to 'Коллбеки', admin_callbacks_path
      %li.list-group-item= link_to 'Товары', admin_products_path
      %li.list-group-item= link_to 'Новый товар', new_admin_product_path
  .col-sm-3
    %ul.list-group
      %li.list-group-item= link_to 'Характеристики', admin_properties_path
      %li.list-group-item= link_to 'Новая характеристика', new_admin_property_path
      %li.list-group-item= link_to 'Фильтры', admin_filters_path
      %li.list-group-item= link_to 'Новый фильтр', new_admin_filter_path
      %li.list-group-item= link_to 'Значения фильтров товаров', admin_filter_values_path
      %li.list-group-item= link_to 'Новое значение фильтра товара', new_admin_filter_value_path
  .col-sm-3
    %ul.list-group
      %li.list-group-item= link_to 'Поставщики', admin_vendor_merchants_path
      %li.list-group-item= link_to 'Новый поставщик', new_admin_vendor_merchant_path
      %li.list-group-item= link_to 'Товары по прайсам', admin_vendor_products_path
      %li.list-group-item= link_to 'Настройки', admin_confs_path
      %li.list-group-item= link_to 'Разметки', admin_markups_path
      %li.list-group-item= link_to 'Новая разметка', new_admin_markup_path
      %li.list-group-item= link_to 'Файловый менеджер', uploaded_files_path(:root)
  .col-sm-3
    %ul.list-group
      %li.list-group-item= link_to 'Категории', admin_categories_path
      %li.list-group-item= link_to 'Новая категория', new_admin_category_path
      %li.list-group-item= link_to 'Меню', admin_taxons_path
      %li.list-group-item= link_to 'Новое меню', new_admin_taxon_path
      %li.list-group-item= link_to 'Бренды', admin_brands_path
      %li.list-group-item= link_to 'Новый бренд', new_admin_brand_path

app/views/shared/_aside.html.haml
%section.aside{ itemtype: "http://schema.org/LocalBusiness", itemscope: '' }
  %h4.text-center Доставка
  .row
    .col-md-4
      = image_tag('delivery.png', class: 'img-responsive')
    .col-md-8
      Срок доставки: 1 - 3 дня.
      %br/
      Cамовывозом - бесплатно.
      %br/
      Курьером - до 8 кг - от 30 грн.
      %br/
      Отправляем через курьерские службы.
  %hr/
  %h4.text-center Оплата
  .row
    .col-md-4
      = image_tag('pay.png', class: 'img-responsive')
    .col-md-8
      <b>Наличными</b> - оплата в нашем офисе.<br/>
      <b>Безнал</b> - банковская карта, через онлайн банк, либо терманалы соответствующего банка.
  %hr/
  %h4.text-center
    Режим работы интернет-магазина
    %span{ itemprop: 'name' } Evotex
  .row
    .col-md-12
      %p ПН &ndash; ПТ: с 9:00 до 19:00
      %p СБ: с 10:00 до 16:00
      %p ВС: выходной
      %p Офис в городе Харькове: ул.Гамарника 7/9

  %hr/
  %h4.text-center Контактная информация
  .row
    .col-md-12.aside_phones
      = image_tag('life.png', alt: 'life :)', title: 'life :)')
      %span{ itemprop: 'telephone' } (093) 805–33–00
      %br/
      = image_tag('ks.png', alt: 'Киевстар', title: 'Киевстар')
      %span{ itemprop: 'telephone' } (098) 118–33–00
      %br/
      = image_tag('mts.png', alt: 'mts', title: 'mts')
      %span{ itemprop: 'telephone' } (095) 387–33–00
      %br/
      = image_tag('stationary.png', alt: 'Городской', title: 'Городской')
      %span{ itemprop: 'telephone' } (057) 731–30–38

app/views/shared/_catalog_modals.html.haml
.modal.fade{ id: 'instant-checkout', tabindex: -1, 'data-backdrop' => 'static', 'data-keyboard' => 'false' }
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{ 'data-dismiss' => 'modal', type: :button }
          %i.glyphicon.glyphicon-remove-circle
        %h4.modal-title Загрузка...
      .modal-body
        .row
          .col-sm-12
            .product_instant-modal
          .col-sm-12
            .order-form
              Пожалуйста, подождите
.modal.fade{ id: 'callback', tabindex: -1 }
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{ 'data-dismiss' => 'modal', type: :button }
          %i.glyphicon.glyphicon-remove-circle
        %h4.modal-title Обратный звонок
      = form_for Callback.new(name: current_user.try(:name), phone: current_user.try(:phone) ), url: callback_user_path do |f|
        .modal-body
          = field_for f, :name, :text_field, required: true
          = field_for f, :phone, :text_field, required: true
          = field_for f, :body, :text_area, rows: 10, required: true
        .modal-footer
          .text-right= f.submit 'Заказать обратный звонок', class: 'btn btn-warning'

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  #error_explanation
    .well.well-sm
      .alert.alert-danger
        #{pluralize(object.errors.count, "ошибка", "ошибок")}.
      %ul.list-group
        - object.errors.full_messages.each do |msg|
          %li.list-group-item
            * #{msg}

app/views/shared/_flash_bar.html.haml
- if flash.present?
  = render 'shared/google_adwords'
  .container
    .row
      .col-sm-6.col-sm-offset-3
        - flash.each do |name, msg|
          = content_tag :div, :class => "alert alert-#{name == 'alert' ? "danger" : "success" } alert-dismissable", :role => "alert" do
            %button.close{:type => "button", :data => {:dismiss => "alert"} }
              %i.glyphicon.glyphicon-remove-circle
              %span.sr-only Закрыть
            = msg

app/views/shared/_footer_bar.html.haml
%footer.jumbotron.bg-main-color
  .container-fluid
    .row
      .col-sm-4
        - cache [ 'logo', Markup.pages ] do
          = render 'shared/pages_menu'
        = Conf['ck.footer1'].html_safe
      .col-sm-4
        = Conf['ck.footer2'].html_safe
      .col-sm-4

        = Conf['ck.footer3'].html_safe
    .row
      .col-xs-12.text-right
        = link_to '/price_full.xml', class: 'btn btn-xs btn-primary', title: 'Скачать прайс (XML)' do
          %i.glyphicon.glyphicon-list-alt
          Скачать прайс (XML)
    - if current_user.try(:admin?)
      %br/
      .row
        = render 'shared/admin_extended_footer_menu'

app/views/shared/_head_assets.html.haml
= stylesheet_link_tag 'application', 'catalog'
%link{ href: 'https://fonts.googleapis.com/css?family=Exo+2&subset=latin,cyrillic', rel: 'stylesheet', type: 'text/css' }

app/views/shared/_main_search_bar.html.haml
- @q ||= Catalog::Product.ransack
- @random_search_word ||= Catalog::Product.order("RANDOM()").first.try(:name).to_s.split.first.presence

= search_form_for @q, url: search_products_path, id: 'main_search_form' do |f|
  .input-group
    = f.search_field :main_search, class: 'form-control', placeholder: 'Поиск по сайту...', required: true, autocomplete: :off
    .input-group-btn= f.submit 'Найти', class: 'btn btn-success'
.product_autocomplete
  .product_autocomplete_inner{ 'data-search-autocomplete' => true }
- if @random_search_word
  Например:
  = link_to @random_search_word, '#', class: 'search-example'

app/views/shared/_modals.html.haml
.modal.fade{ id: 'vendor-product-scraper-window', tabindex: -1, 'data-backdrop' => 'static', 'data-keyboard' => 'false' }
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{ 'data-dismiss' => 'modal', type: :button }
          %i.glyphicon.glyphicon-remove-circle
        %h4.modal-title loading...
      .modal-body
        .row
          .col-xs-12
            \...

app/views/shared/_pages_menu.html.haml
%ul.list-inline
  %li
    = link_to 'Главная', root_path, class: 'btn btn-xs btn-info'
  - Markup.pages.includes(:seo).sort_by(&:position).each do |page|
    %li
      = link_to page.name, static_page_path(slug: page.slug, id: page.id), class: 'btn btn-xs btn-info', title: page.seo.try(:title)
  %li
    = link_to 'Помощь', help_pages_path, class: 'btn btn-xs btn-info'

app/views/shared/_product_card_footer_bar.html.haml
%footer.bg-main-color
  .container-fluid
    .row
      .col-sm-2
        %h4 Evotex &copy; 2013 - 2016

app/views/shared/_product_card_search_bar.html.haml
- @q ||= Catalog::Product.ransack
- @random_search_word ||= Catalog::Product.order("RANDOM()").first.name.split.first

= search_form_for @q, url: search_products_path, id: 'main_search_form', class: 'navbar-form' do |f|
  .form-group{ display: :inline }
    .input-group{ display: :table }
      = f.search_field :main_search, class: 'form-control', placeholder: 'Поиск по сайту...', required: true, autocomplete: :off
      %span.input-group-btn{ style: "width:1%;" }
        %button.btn.btn-success{ type: :submit }
          %span.glyphicon.glyphicon-search


    .product_autocomplete
      .product_autocomplete_inner{ 'data-search-autocomplete' => true }

app/views/shared/_slides.html.haml
#slides.carousel.slide{ data: { ride: 'carousel' } }
  %ol.carousel-indicators
    - Markup.active.slides.count.times do |i|
      %li{ data: { target: '#slides', 'slide-to' => i, class: ('active' if i == 0) } }
  .carousel-inner
    - Markup.active.slides.each_with_index do |slide, index|
      .item{ class: ('active' if index == 0) }
        = slide.body.html_safe
  %a.left.carousel-control{ href: '#slides', data: { slide: :prev } }
    %i.glyphicon.glyphicon-chevron-left
  %a.right.carousel-control{ href: '#slides', data: { slide: :next } }
    %i.glyphicon.glyphicon-chevron-right

app/views/shared/_top_bar.html.haml
.jumbotron.bg-main-color.top-bar
  #animated-header.hidden-xs
    %canvas#animated-header-canvas
  .container
    .row
      .col-sm-3
        = Conf['ck.logo'].html_safe
      .col-sm-6
        - cache [ 'logo', Markup.pages ] do
          = render 'shared/pages_menu'
        = Conf['ck.phones'].html_safe
        = render 'shared/main_search_bar'
      .col-sm-3
        %h2 Режим работы
        = Conf['ck.mode'].html_safe
.container.taxons-container

  - cache ['catalog_menu', Catalog::Taxon.pluck(:updated_at).map(&:to_i)] do
    = render 'shared/menu_bar'