config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  get 'robots.txt', to: 'catalog#robots'
  get 'error/:number', to: 'catalog#error', as: :error

  post 'p/comment', to: 'products#add_comment', as: :product_comment
  get '/c/:id/compare', to: 'categories#compare', as: :compare
  post '/c/:id/compare/:product_id', to: 'categories#add_to_compare', as: :add_to_compare
  delete '/c/:id/compare/:product_id', to: 'categories#remove_from_compare', as: :remove_from_compare

  get 'p/:slug-:id', to: 'products#show', as: :p
  get 't/:slug-:id', to: 'taxons#show', as: :t
  get 'c/:slug-:id', to: 'categories#show', as: :c
  get 'pages/:slug-:id', to: 'catalog#static_page', as: :static_page
  get 'help/:slug-:id', to: 'catalog#show_help_page', as: :help_page

  # Old links for SEO
  get 'p/:slug/:id', to: redirect('/p/%{slug}-%{id}')
  get 't/:slug/:id', to: redirect('/t/%{slug}-%{id}')
  get 'c/:slug/:id', to: redirect('/c/%{slug}-%{id}')
  get 'pages/:slug/:id', to: redirect('/pages/%{slug}-%{id}')
  get 'help/:slug/:id', to: redirect('/help/%{slug}-%{id}')

  devise_for :users
  resource :user, only: [:show, :update] do
    post :callback
  end

  get 'help', to: 'catalog#help_pages', as: :help_pages
  get 'p/search', to: 'products#search', as: :search_products

  resource :order, only: [:show, :update] do
    post :checkout
    patch 'update_lineitem_count', to: 'orders#update_lineitem_count', as: :update_lineitem_count
    post 'add_product/:product_id', to: 'orders#add_product', as: :add_product
    delete 'remove_product/:product_id', to: 'orders#remove_product', as: :remove_product
  end

  namespace :admin do
    get '/', to: 'base#dashboard'
    post 'internal/:act', to: 'base#internal', as: :internal_action
    post 'binding/:product_id/:vendor_product_id', to: 'binding#bind'
    delete 'binding/:vendor_product_id', to: 'binding#unbind'
    namespace :autocomplete do
      get :properties
    end
    resources :taxons do
      post :sort, on: :collection
    end
    resources :products do
      member do
        post :update_from_marketplace
        post :recount
        post :copy_filters
        post :copy_properties
        patch 'product_filter_values/:pfv_id', to: 'products#update_product_filter_value', as: :update_pfv
      end
      collection do
        get :search
        get :search_marketplaces
        post :create_from_marketplace
      end
      resources :product_properties, only: [:create, :update] do
        member do
          patch :update, to: 'properties#update_product_property', as: :update
          delete :destroy, to: 'properties#destroy_product_property', as: :destroy
        end
        collection do
          post :create, to: 'properties#create_product_property', as: :create
        end
      end
      resources :properties, only: [:create, :destroy] do
        collection do
          patch :reorder_product
        end
      end

    end
    resources :categories, except: [:show] do
      post :reorder_all_properties
      post :reorder_filters
      post :add_filter
      post :add_filter_value
      delete 'remove_filter/:filter_id', to: 'categories#remove_filter', as: :remove_filter
      delete 'remove_filter_value/:filter_value_id', to: 'categories#remove_filter_value', as: :remove_filter_value
      resources :properties, only: [] do
        member do
          delete :'destroy_category_property', as: :destroy
        end
        collection do
          post :create_category_property, as: :create

          patch :reorder_category
          post :reorder_category_all
        end
      end
      collection do
        get :search
      end
    end

    resources :brands, except: [:show] do
      collection do
        get :search
      end
    end
    resources :confs, only: [:index, :update]
    resources :markups, except: [:show] do
      get :search, on: :collection
    end
    resources :orders, except: [:show] do
      get :search, on: :collection
    end
    resources :users, except: [:show] do
      get :search, on: :collection
    end
    namespace :vendor do
      resources :products, only: [:index, :show, :update] do
        get :search, on: :collection
        post :toggle_activation, on: :member
      end
      resources :merchants, except: [:show] do
        post :pricelist, on: :member
        get :auto_price, on: :member
      end
    end
    resources :callbacks, except: [:new, :create, :show] do
      get :search, on: :collection
    end
    resources :comments, except: [:new, :create, :show] do
      get :search, on: :collection
    end
    resources :markups, except: :show
    resources :users, except: [:new, :create, :show]
    resources :user_actions, only: :index do
      get :search, on: :collection
    end
    resources :filters, except: :show
    resources :filter_values, except: :show do
      get :search, on: :collection
    end
    resources :properties
  end
  mount Ckeditor::Engine => '/ckeditor'
end

app/models/catalog/filter_value.rb
class Catalog::FilterValue < ActiveRecord::Base
  before_create :set_position
  validates :name, :filter, presence: true
  validates :name, uniqueness: { case_sensitive: false, scope: [:catalog_filter_id] }
  belongs_to :filter, class_name: Catalog::Filter, foreign_key: :catalog_filter_id
  class << self
    def to_group
      all.group_by(&:catalog_filter_id)
    end

    def count_w(id, params, products)
      # TODO: Optimize filters pluses
      s = ''
      init_count = products.count
      p = Marshal.load(Marshal.dump(params))
      filtered = p[:f].to_s.split(',').map(&:strip)
      siblings = Catalog::FilterValue.includes(filter: :values).find(id).filter.values.map(&:id).map(&:to_s)
      checked_state = filtered.include?(id)
      action = checked_state ? :delete : :push
      p[:f] = p[:f].to_s.split(',').map(&:strip).send(action, id).join(',')

      count = products.unscoped.with_price.by_category_params(p).count

      if (filtered & siblings).present?
        if count == init_count
          count = 0
        elsif count > init_count
          count = count - init_count
        end
        s = '+'
      end

      return "#{s}#{count}"
    end
  end

  private

  def set_position
    max_position = if filter
      filter.values.max_by(&:position).try(:position).to_i
    else
      100
    end
    self.position = max_position + 1
  end

end

app/controllers/admin/filter_values_controller.rb
class Admin::FilterValuesController < Admin::BaseController
  before_action :check_admin_permissions
  before_action :set_filter_value, only: [:edit, :update, :destroy]

  def index
    @q = Catalog::FilterValue.ransack
    @filter_values = Catalog::FilterValue.all.order('created_at DESC').page(params[:page])
  end

  def search
    params[:q].each_value do |v| v.strip! end if params[:q]
    @q = Catalog::FilterValue.ransack(params[:q])
    @filter_values = @q.result.order('created_at DESC').page(params[:page])
    render :index
  end

  def new
    @filter_value = Catalog::FilterValue.new
  end

  def create
    @filter_value = Catalog::FilterValue.new(filter_value_params)
    if @filter_value.save
      redirect_to admin_filter_values_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @filter_value.update(filter_value_params)
      redirect_to admin_filter_values_path
    else
      render 'edit'
    end
  end

  def destroy
    @filter_value.destroy
    redirect_to admin_filter_values_path
  end

  private

  def filter_value_params
    params.require(:catalog_filter_value).permit(:name, :display_name, :catalog_filter_id)
  end

  def set_filter_value
    @filter_value = Catalog::FilterValue.find(params[:id])
  end
end

app/views/admin/filter_values/edit.html.haml
.page-header
  %h1 Изменить значение фильтра
.row
  = form_for(@filter_value, url: admin_filter_value_path) do |f|
    %ul.list-group
      %li.list-group-item
        = f.label :catalog_filter_id, "Фильтр"
        = f.select :catalog_filter_id, Catalog::Filter.all.map { |f| [f.name, f.id] }, {},class: 'form-control'
      %li.list-group-item= field_for(f, :name)
      %li.list-group-item= field_for(f, :display_name)
    = f.submit 'Отправить', class: 'btn btn-success'

app/views/admin/filter_values/index.html.haml
.jumbotron
  = search_form_for @q, url: search_admin_filter_values_path do |f|
    .row
      .col-sm-8.col-sm-offset-2.text-center
        .input-group
          = f.search_field :name_cont, class: 'form-control', placeholder: 'Название'
          .input-group-btn= f.submit 'Найти', class: 'btn btn-success'
.page-header
  = link_to new_admin_filter_value_path, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    Новое значение фильтра
  %h1 Значения фильтров
.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Имя
        %th Отображаемое имя
    %tbody
      - @filter_values.each do |filter_value|
        %tr
          %td
            = filter_value.name
          %td
            = filter_value.display_name
          %td
            = link_to 'Изменить', edit_admin_filter_value_path(filter_value)
          %td
            = link_to admin_filter_value_path(filter_value), method: :delete, class: 'btn btn-xs btn-danger', 'data-confirm' => 'Вы уверены?' do
              %i.glyphicon.glyphicon-remove
    %tfoot
      %tr
        %td.text-center{ colspan: 6 }
          = paginate @filter_values

app/views/admin/filter_values/new.html.haml
.page-header
  %h1 Новое значение фильтра
.row
  = form_for(@filter_value, url: admin_filter_values_path) do |f|
    %ul.list-group
      %li.list-group-item
        = f.label :catalog_filter_id, "Фильтр"
        = f.select :catalog_filter_id, Catalog::Filter.all.map { |f| [f.name, f.id] }, {},class: 'form-control'
      %li.list-group-item= field_for(f, :name)
      %li.list-group-item= field_for(f, :display_name)
    = f.submit 'Отправить', class: 'btn btn-success'